version: "3.1"
services:
  client:
    build:
      context: ./client
    restart: always
    networks:
      - sela
    ports:
      - 3000:3000
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    depends_on:
      - client
    networks:
      - sela
    #   - server
#   server:
#     build:
#       context: ./server
#     restart: always
networks:
  sela:
    driver: bridge
